version: 0.0
os: linux

files:
  - source: /
    destination: /opt/tomcat/webapps


hooks:
    ApplicationStop:
    - location: /scripts/shutdown.sh
      timeout: 300
      runas: root
    ApplicationStart:
    - location: /scripts/startup.sh
      timeout: 300
      runas: root

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
